services:
  backend:
    build: ../backend
    container_name: meal_planner_backend
    # ports:
    #   - "8001:8000" # Plus nécessaire grâce au proxy Nginx
    volumes:
      - ../backend:/app
      - images_data:/app/static/images
    environment:
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
    networks:
      - mealnet
    depends_on:
      db:
        condition: service_healthy
    command: sh /app/start.sh

  frontend:
    build: ../frontend
    container_name: meal_planner_frontend
    ports:
      - "3000:80"
    volumes:
      - ../frontend:/usr/share/nginx/html
      - ../frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - mealnet
    depends_on:
      - backend

  db:
    image: mysql:8.4
    container_name: meal_planner_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    # ports:
    #   - "3306:3306"  # Sécurité : On ne l'expose pas, accès via Adminer ou App interne uniquement
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mealnet
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mealnet

volumes:
  db_data:
  images_data:


networks:
  mealnet:
